version: "3.8"
services:
  api:
    container_name: api-container
    restart: always
    build: ./backend
    ports:
      - "4000:4000"

  client:
    container_name: client-container
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
